name: "Release"

on:
  release:
    types:
      - released

jobs:
  release:
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up poetry
        uses: snok/install-poetry@v1
        with:
          python-version: '3.11'
          cache: true

      - name: Install dependencies
        run: |
          poetry install --without dev

      - name: Release to PyPI
        env:
          POETRY_PYPI_TOKEN_ADALA: ${{ secrets.PYPI_APIKEY }}
        run: |
          poetry publish
